export default {
  code: 0,
  message: "0",
  ttl: 1,
  data: {
    mid: 2042149112,
    name: "b站_EN組",
    sex: "保密",
    face: "http://i0.hdslb.com/bfs/face/member/noface.jpg",
    sign: "",
    rank: 10000,
    level: 3,
    jointime: 0,
    moral: 0,
    silence: 0,
    coins: 0,
    fans_badge: false,
    fans_medal: { show: false, wear: false, medal: null },
    official: { role: 0, title: "", desc: "", type: -1 },
    vip: {
      type: 0,
      status: 0,
      due_date: 0,
      vip_pay_type: 0,
      theme_type: 0,
      label: {
        path: "",
        text: "",
        label_theme: "",
        text_color: "",
        bg_style: 0,
        bg_color: "",
        border_color: "",
      },
      avatar_subscript: 0,
      nickname_color: "",
      role: 0,
      avatar_subscript_url: "",
    },
    pendant: {
      pid: 0,
      name: "",
      image: "",
      expire: 0,
      image_enhance: "",
      image_enhance_frame: "",
    },
    nameplate: {
      nid: 0,
      name: "",
      image: "",
      image_small: "",
      level: "",
      condition: "",
    },
    user_honour_info: { mid: 0, colour: null, tags: [] },
    is_followed: false,
    top_photo:
      "http://i1.hdslb.com/bfs/space/cb1c3ef50e22b6096fde67febe863494caefebad.png",
    theme: {},
    sys_notice: {},
    live_room: {
      roomStatus: 0,
      liveStatus: 0,
      url: "",
      title: "",
      cover: "",
      online: 0,
      roomid: 0,
      roundStatus: 0,
      broadcast_type: 0,
    },
    birthday: "",
    school: { name: "" },
    profession: { name: "" },
    tags: null,
    series: { user_upgrade_status: 3, show_upgrade_window: false },
  },
};
